#!/usr/bin/env python

# ================================================================================
# =                                   BULLETS                                    =
# ================================================================================

# Takes multi-line text from clipboard and adds bullet points to each line.

import sys

import pyperclip

bullet = "-"

if len(sys.argv) > 1:
    bullet = sys.argv[1]

pyperclip.copy(
    "\n".join([bullet + " " + line for line in pyperclip.paste().splitlines()])
)
