#!/usr/bin/env python

# ================================================================================
# =                                     CWD                                      =
# ================================================================================

# Copies current working directory to clipboard.

import os
import sys

import pyperclip

if len(sys.argv) > 1:
    os.chdir(sys.argv[1])

pyperclip.copy(os.getcwd())
