#!/usr/bin/env python

# ================================================================================
# =                                     CWFM                                     =
# ================================================================================

# Copies a users warframe.market listings to clipboard ready for in game pasting.

import sys

import pyperclip
import requests


def build_id_to_name_mapping() -> dict[str, str]:
    """Build id to name mapping dictionary."""
    r = requests.get("https://api.warframe.market/v2/items")
    r.raise_for_status()

    id_to_name = {}

    for item in r.json()["data"]:
        id_to_name[item["id"]] = item["i18n"]["en"]["name"]

    return id_to_name


def gather_user_listings(user: str) -> list[str]:
    """Gather listings for a specific user."""
    r = requests.get(f"https://api.warframe.market/v2/orders/user/{user.lower()}")
    r.raise_for_status()

    listings = []

    for item in r.json()["data"]:
        listings.append(item["itemId"])

    return listings


def convert_ids_to_names(listings, id_to_name) -> list[str]:
    """Convert listing IDs to in game item names."""
    mapped_listings = []
    for listing in listings:
        mapped_listings.append(id_to_name[listing])

    return mapped_listings


def format_and_copy_listings(name_listings) -> None:
    """Format and copy listings into a pastable string."""
    formatted_listings = []
    for listing in name_listings:
        formatted_listings.append("[" + listing + "]")
    pyperclip.copy(" ".join(formatted_listings))


def main() -> None:
    """Main entry point."""
    id_to_name = build_id_to_name_mapping()

    user_id = sys.argv[1] if len(sys.argv) > 1 else "bhwsg"
    id_listings = gather_user_listings(user_id)

    name_listings = convert_ids_to_names(id_listings, id_to_name)

    format_and_copy_listings(name_listings)


if __name__ == "__main__":
    main()
