#!/usr/bin/env python

# ================================================================================
# =                                     QAUR                                     =
# ================================================================================

# Opens AUR package search results in the browser from arguments

import sys
import webbrowser

webbrowser.open(f"https://aur.archlinux.org/packages/?K={' '.join(sys.argv[1:])}")
