#!/usr/bin/env python

# ================================================================================
# =                                     QAUR                                     =
# ================================================================================

# Opens AUR package search results in the browser from arguments

import subprocess
import sys

query = " ".join(sys.argv[1:])
subprocess.run(
    [
        "/mnt/c/Program Files/Mozilla Firefox/firefox.exe",
        f"https://aur.archlinux.org/packages/?K={query}",
    ]
)
