#!/usr/bin/env python

# ================================================================================
# =                                     QAUR                                     =
# ================================================================================

# Opens AUR search results in the browser from arguments

import sys
import webbrowser

webbrowser.open("https://aur.archlinux.org/packages/?K=" + " ".join(sys.argv[1:]))
