#!/usr/bin/env python

# ================================================================================
# =                                   QCLAUDE                                    =
# ================================================================================

# Opens a new Claude chat in the browser and asks the question from arguments

import subprocess
import sys

query = "+".join(sys.argv[1:])
subprocess.run(
    [
        "/mnt/c/Program Files/Mozilla Firefox/firefox.exe",
        f"https://claude.ai/new?q={query}",
    ]
)
