#!/usr/bin/env python

# ================================================================================
# =                                   QGITHUB                                    =
# ================================================================================

# Opens GitHub repository search results in the browser from arguments

import subprocess
import sys

query = "+".join(sys.argv[1:])
subprocess.run(
    [
        "/mnt/c/Program Files/Mozilla Firefox/firefox.exe",
        f"https://github.com/search?q={query}&type=repositories",
    ]
)
