#!/usr/bin/env python

# ================================================================================
# =                                   QGITHUB                                    =
# ================================================================================

# Opens GitHub repository search results in the browser from arguments

import sys
import webbrowser

webbrowser.open(
    f"https://github.com/search/?q={' '.join(sys.argv[1:])}&type=repositories"
)
