#!/usr/bin/env python

# ================================================================================
# =                                   QGOOGLE                                    =
# ================================================================================

# Opens google search results in the browser from arguments

import subprocess
import sys

query = "+".join(sys.argv[1:])
subprocess.run(
    [
        "/mnt/c/Program Files/Mozilla Firefox/firefox.exe",
        f"https://www.google.com/search?q={query}",
    ]
)
