#!/usr/bin/env python

# ================================================================================
# =                                   QPACMAN                                    =
# ================================================================================

# Opens pacman package search results in the browser from arguments

import sys
import webbrowser

webbrowser.open(f"https://archlinux.org/packages/?q={' '.join(sys.argv[1:])}")
