#!/usr/bin/env python

# ================================================================================
# =                                    QPYPI                                     =
# ================================================================================

# Opens PyPI package search results in the browser from arguments

import subprocess
import sys

query = " ".join(sys.argv[1:])
subprocess.run(
    [
        "/mnt/c/Program Files/Mozilla Firefox/firefox.exe",
        f"https://pypi.org/search/?q={query}",
    ]
)
