#!/usr/bin/env python

# ================================================================================
# =                                    QPYPI                                     =
# ================================================================================

# Opens PyPI package search results in the browser from arguments

import sys
import webbrowser

webbrowser.open(f"https://pypi.org/search/?q={' '.join(sys.argv[1:])}")
