#!/usr/bin/env python

# ================================================================================
# =                                   SHOWMAP                                    =
# ================================================================================

# Launches a map in the browser using address from command line or clipboard

import sys
import webbrowser

import pyperclip

address = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else pyperclip.paste()

webbrowser.open(f"https://www.openstreetmap.org/search?query={address}")
